In [25]:
 # Given a matrix mat of size 3 x 3. Find the maximum numbers from each row, say N1, N2 and N3. Result in a matrix by adding:


import numpy as np
mat = np.array([[10,5,9],
                [2,20,6],
                [8,3,30]]).reshape(3,3)
mat


array([[10,  5,  9],
       [ 2, 20,  6],
       [ 8,  3, 30]])

In [26]:
[N1, N2, N3] = mat.max(axis=1)
n = [N1, N2, N3]
n

[10, 20, 30]

In [10]:
mat_new = np.add(mat, np.diag([20,20,20]))
mat_new

array([[30,  5,  9],
       [ 2, 40,  6],
       [ 8,  3, 50]])

In [27]:
mat[np.tril_indices(3, -1)] += N3
mat

array([[10,  5,  9],
       [32, 20,  6],
       [38, 33, 30]])

In [28]:
mat[np.triu_indices(3, 1)] += N1
mat

array([[10, 15, 19],
       [32, 20, 16],
       [38, 33, 30]])

In [29]:
mat = mat + np.diag([N2, N2, N2])
mat

array([[30, 15, 19],
       [32, 40, 16],
       [38, 33, 50]])

In [32]:
print(mat.sum(axis = 0).shape)
print(mat.sum(axis = 1).shape)

(3,)
(3,)
