In [1]:
import numpy as np

In [2]:
# 1. Create a 4 x 4 matrix and add values 4,5,6 above the parent diagonal.

mat = np.matrix([[0,4,0,0],
                [0,0,5,0],
                [0,0,0,6],
                [0,0,0,0]])
print(mat)

[[0 4 0 0]
 [0 0 5 0]
 [0 0 0 6]
 [0 0 0 0]]


In [55]:
mat = np.diag([4,5,6],1)
mat

array([[0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6],
       [0, 0, 0, 0]])

In [21]:
# 2. Given a Numpy array arr = np.arange(11), negate all the elements between 6 and 10.

arr = np.arange(11)
arr[(arr>=6) & (arr<=10)] *= -1 
arr

array([  0,   1,   2,   3,   4,   5,  -6,  -7,  -8,  -9, -10])

array([], dtype=int32)

In [22]:
arr3=np.arange(11,dtype='int64') 
print(np.where((arr3>6) & (arr3<10),arr3*-1,arr3))

[ 0  1  2  3  4  5  6 -7 -8 -9 10]


In [23]:
# 3. Given a matrix mat and an array arr, for each row of the matrix if elements of Column 1 are equal to the corresponding element of the array, then print the corresponding value of Column 2 of the matrix.

 
import numpy as np
mat = np.array([['abc','A'],['def','B'],['ghi','C'],['jkl','D']])
arr = np.array(['abc','dfe','ghi','kjl']) 
 


In [28]:
for i in range(mat.shape[0]):
    if mat[i][0] in arr:
        print(mat[i][1])

A
C


In [27]:
mat.shape[0]

4

In [32]:
# 4. Given a matrix mat, sort it by the second column.

 
import numpy as np
mat = np.array([[1,21,3],[5,4,2],[56,12,4]])
mat


array([[ 1, 21,  3],
       [ 5,  4,  2],
       [56, 12,  4]])

In [34]:
mat[:,1]

array([21,  4, 12])

In [35]:
mat[:, 1].argsort()

array([1, 2, 0], dtype=int64)

In [36]:
mat[mat[:,1].argsort()]

array([[ 5,  4,  2],
       [56, 12,  4],
       [ 1, 21,  3]])

In [37]:
# 5. Given an array arr, find the top 4 maximum values.

 
import numpy as np
arr = np.array([90, 14, 24, 13, 13, 590, 0, 45, 16, 50])
arr

array([ 90,  14,  24,  13,  13, 590,   0,  45,  16,  50])

In [39]:
arr[arr.argsort()[-4:]]

array([ 45,  50,  90, 590])

In [40]:
# 6. Find the nearest number from the given number in an array.

 
arr = np.array([10,55,22,3,6,44,9,54])
nearest_to = 50




In [44]:
def fun(x):
    return abs(x-50)

In [45]:
funV = np.vectorize(fun)

In [47]:
arrV = funV(arr)
arrV

array([40,  5, 28, 47, 44,  6, 41,  4])

In [49]:
arr[arrV.argsort()[0]]

54