In [1]:
import numpy as np

In [2]:
 
S_X = np.array([[2, 5, 6, 5],
               [4, 8, 6, 5]])
print(S_X)
# [[2 5 6 5]
#  [4 8 6 5]]
S_Y = np.array([[6, 7, 5, 9],
               [7, 5, 6, 4]])
print(S_Y)
# [[6 7 5 9]
#  [7 5 6 4]] 
 


[[2 5 6 5]
 [4 8 6 5]]
[[6 7 5 9]
 [7 5 6 4]]


In [3]:
print(S_X-S_Y)

[[-4 -2  1 -4]
 [-3  3  0  1]]


In [4]:
print(S_X<2)

[[False False False False]
 [False False False False]]


In [5]:
np.cumsum(S_X, axis=1)

array([[ 2,  7, 13, 18],
       [ 4, 12, 18, 23]], dtype=int32)